# Should setup database, travis file not completed
language : python
python:
  - "2.7"
before_install:
  - "git clone git://github.com/n1k0/casperjs.git"
  - "sudo ln -s `pwd`/casperjs/bin/casperjs /usr/local/bin"

services : postgresql
# command to install dependencies
install: 
  - pip install -r requirements.txt --use-mirrors

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

# command to run tests
script: 
  - python manage.py syncdb --all --noinput
  - python manage.py migrate --fake
  - python manage.py test
